### PR TITLE
Add support for el9 (CANDLEPIN-376)

### PR DESCRIPTION
**Pull request by Januson**
Note: In order to get ruby installed in el9 it needs a compatible version of openssl. There is a bug in the ansible ruby role we were using to install rvm/ruby which prevents the role from skipping the installation of ruby. I forked it and fixed this so that we can install openssl in between the installation of rvm and ruby.

### CODE REVIEW

**Comment by Ceiu** [comment]
There's a lot of shifting around that Ruby stuff that could use some explanation. Have we tried updating our Ruby version such that we can reference a newer version of OpenSSL, or not need it at all? Which components are we still stuck on that need it?
With the addition of RHEL9, we can drop the RHEL7 box, so if that's holding us back, it could be dropped if it makes the transition easier.

Additionally, as far as the skipping of ruby goes, have we tried making the dependency reference conditional, rather than forking the rvm role entirely?

**Review by Ceiu — CHANGES_REQUESTED** [review]
Most of this looks good, and some of the organization of packages and whatnot is appreciated. Though the ruby issues give me a lot of pause without more information.

Given how much of the DB stuff is identical between the systems, we could probably move those to common to avoid duplicating that repeatedly. In the case of EL7 where the paths differ slightly, we could var those out and specify the home directory or some such when invoking the task.

**Comment by Januson** [comment]
@Ceiu Basically rvm fails to install ruby. The only way I found around this issue is to install openssl before the installation of ruby itself with 'rvm pkg'. To do this I had to move the use of ruby role into a task. I tried other things as well like installing a compat package but this is the only thing that worked.

Updating our ruby setup might work but it haven't been updated in quite a while so who knows what breaking changes await there.

**Comment by Januson** [comment]
Looks like there is some issue with deduplication of the db tasks. I'll post it as a separate PR.

**Comment by Ceiu** [comment]
This hasn't been merged yet (haven't had a moment to dive into manual testing), so let's just fix it here.

**Comment by nikosmoum** [comment]
Closing this since we will make this change after the copy/merge of the ansible role into the main candlepin repo.

**Pull request closed without merging**
