### PR TITLE
Updated Java optional args for remote debugging

### PR DESCRIPTION
**Pull request by wolfdale**
Changes -
- Updated the Java Opts for remote debugging to support JDK 11.
- Added OpenJDK 8 dependency(To be backward compatible)
- Added config changes to set Java 11 as default environment.

### CODE REVIEW

**Comment by barnabycourt** [comment]
Does this also work if someone wants to boot an older candlepin on java 8?

**Comment by wolfdale** [comment]
NO. These Java optional agrs will not work with Java 8. To do this we need to manually update 
this in tomcat.conf.

Adding more changes to this PR to be backward compatible with Java 8. After merging this PR. 
Vagrant box will have both Java 8 & Java 11 (as default) available.

To switch to Java 8 we need to manually configure few things after booting vagrant box - 

1) Switch to correct Java version (Select Java 8)
```sudo update-alternatives --config java```
```sudo update-alternatives --config javac```

2) Set JAVA_HOME to correct version in ```bashrc.```
3) Manually edit tomcat.conf to update these config properties.
```JAVA_HOME="/usr/lib/jvm/jre-1.8.0/"```
```JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n```

4) Restart Tomcat.

**Comment by sonalidhome** [comment]
I have tried this in different versions of Candlepin. 
Vagrant box fails on `vagrant up` in older versions at `build and deploy candlepin server` task. After doing `vagrant ssh`, I configured Java 8 manually in a vagrant box as per the details mentioned in the comment.  And redeployed the candlepin with `./server/bin/deploy -g`. And it worked. This could be an overhead every time when we switch to an older version. 
We also need to explain and document these steps explicitly in the README file.

**Comment by sonalidhome** [comment]
@barnabycourt @Ceiu Any thoughts on this?

**Comment by Ceiu** [comment]
This mostly lines up with my own experience with Java11 and the Vagrant VMs. For Java 8, however, I've had to use ```0.0.0.0:8000``` to remote debug from outside the VM to inside.

**Comment by wolfdale** [comment]
@nikosmoum Can you please take a look at this PR. 
It allows us to be compatible with both Java versions & also have changes to allow remote debugging with Java 11.

**Review by nikosmoum — APPROVED** [review]
ACK, but I agree with @sonalidhome that we need another PR to update the README file under https://github.com/candlepin/candlepin/tree/master/vagrant to have a section explaining that by default Java 11 is setup, and what manual steps one needs to take to get it workign with 8.

**Comment by wolfdale** [comment]
Opened a [PR](https://github.com/candlepin/candlepin/pull/2841) to update README file.

**Pull request merged**
